name: Release to PyPI

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/scripts   # where deploy.sh lives

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Run deploy script
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: bash deploy.sh